---
- name: Create dhcpd.conf.d
  file:
    path: /etc/dhcpd.conf.d
    state: directory
    owner: root
    group: wheel
    mode: 0755

- name: Configure dhcpd core
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcpd.conf.d/10-core
    owner: root
    group: wheel
    mode: 0644
  notify:
    - dhcpd

- name: Enable dhcpd
  template:
    src: 10-dhcp.j2
    dest: /etc/rc.conf.local.d/10-dhcp
    owner: root
    group: wheel
    mode: 0644
  notify:
    - rc.conf.local

- name: Install dhcpd-reconf
  copy:
    src: dhcpd-reconf
    dest: /usr/local/sbin/dhcpd-reconf
    owner: root
    group: wheel
    mode: 0755
